### ISSUE TITLE
Typos etc.

### ISSUE THREAD

**Issue by marisacasillas** [jsalt-coml/lena_eval#3]
- move "e.g." to the alphabetical front of its reference list in two different places in paragraph two (beginning "One approach that has been making...")
- Fig 1: some of the black text in the "Segment Counts" section is a bit off the edge of its box
- I wondered how many was "some" in the following sentence "Note that in some cases there was just a little speech; in this case...". Could a % be added?
- "Finally, performance was worst when **included also** overlapping regions"
- Table 5 caption: "only speaker categories are **considers**" (this caption also has some asterisks that I think aren't intentional)
- Figures 2 and 3: "Proportion" seems like an underinformative label for the color density.
- "tends to underestimate turn counts, which is particularly clear when excluding clips with no turns" <- the data in Fig 4 look like it underestimates turn counts when all clips are included and _overestimates_ them when excluding zero-count clips, is that not the case? If so, this needs to be touched up in the discussion when it comes up again, I guess.
- When you come back to the IER in the paragraph starting "Our first set of analyses tested..." I had already forgotten the meaning of the three values—a reminder would be nice!
- Separately researchers should reflect ~about~ **on** the accuracy needed..." (not sure about this one... effin prepositions)
- "Tools and approaches that allow us to tap **into** such recordings' contents..."
- A more general comment was that I found it pretty difficult to synthesize the correlational outcomes, multiple error outcomes, and mixed models for the derived count measures. I know you want to avoid making across-the-board recommendations, but there's just so much information, I can imagine readers being pretty overwhelmed.

Overall: I enjoyed reading this and don't really have further comments. This is a great use of the annotated data we've generated, thanks very much! I hope you get some useful feedback from reviewers :)

**Comment by alecristia** [comment]
@ebergelson I'm a little stuck with this one:

* Figures 2 and 3: "Proportion" seems like an underinformative label for the color density.

Given the caption, it should say percentage (done) and go from 0 to 100 (stumped) so for now I just removed the legend (and perhaps we don't need it)

Also, I think we all agree with Middy on this:

>>> A more general comment was that I found it pretty difficult to synthesize the correlational outcomes, multiple error outcomes, and mixed models for the derived count measures. I know you want to avoid making across-the-board recommendations, but there's just so much information, I can imagine readers being pretty overwhelmed.

I guess it's too late to move stuff to supplementary? Or do you think we can fix that by clarifying in the discussion that these all align rather well?

**Comment by alecristia** [comment]
actually, I think we shouldn't change the manuscript that much, since this is the version ok'd by the reviewer and editor... So I'd still welcome your help if you want to put back the legend, but that can also happen at the proofs stage. I'm turning stuff in & closing this issue now in the meanwhile!

**Comment by alecristia** [comment]
@ebergelson help with one more other thing: in Fig 6, the ` are printed out in the axes. Could we not have those `?

**Comment by alecristia** [comment]
note to self! to generate the word doc version:

- [ ] fix author note
- [ ] add tables 1 and 2
- [ ] add caption Fig 1
- [ ] fix all table and figure caption numbering
